version: '2'

services:
  teakki:
    container_name: teakki_container
    image: registry.cn-hangzhou.aliyuncs.com/teakki/teakki:2.7
    ports:
      - "9001:9002"
    volumes:
      - /teakki_data:/data
